# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Group(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, photo_url: str=None):  # noqa: E501
        """Group - a model defined in Swagger

        :param id: The id of this Group.  # noqa: E501
        :type id: int
        :param name: The name of this Group.  # noqa: E501
        :type name: str
        :param photo_url: The photo_url of this Group.  # noqa: E501
        :type photo_url: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'photo_url': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'photo_url': 'photo_url'
        }
        self._id = id
        self._name = name
        self._photo_url = photo_url

    @classmethod
    def from_dict(cls, dikt) -> 'Group':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Group of this Group.  # noqa: E501
        :rtype: Group
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Group.


        :return: The id of this Group.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Group.


        :param id: The id of this Group.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Group.


        :return: The name of this Group.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Group.


        :param name: The name of this Group.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def photo_url(self) -> str:
        """Gets the photo_url of this Group.


        :return: The photo_url of this Group.
        :rtype: str
        """
        return self._photo_url

    @photo_url.setter
    def photo_url(self, photo_url: str):
        """Sets the photo_url of this Group.


        :param photo_url: The photo_url of this Group.
        :type photo_url: str
        """

        self._photo_url = photo_url
